# Generated by Django 4.0.10 on 2024-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='movie',
        ),
        migrations.AddField(
            model_name='theatre',
            name='movie',
            field=models.ManyToManyField(to='backend.movie'),
        ),
    ]
